config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("phonebook.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("contacts/", include("phonebook.contacts.urls", namespace="contacts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

phonebook/contacts/urls.py
from django.urls import path

from .views import ContactCreateView, ContactDetailView, ContactListView, PhoneNumberCreateView

app_name = "contacts"

urlpatterns = [
    path("", ContactListView.as_view(), name="contact_list"),
    path("create/", ContactCreateView.as_view(), name="contact_create"),
    path("<int:pk>/", ContactDetailView.as_view(), name="contact_detail"),
    path("<int:pk>/phone_number/create/", PhoneNumberCreateView.as_view(), name="phone_number_create"),
]

phonebook/contacts/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class PhoneNumber(models.Model):
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE, related_name="phone_numbers")
    number = models.CharField(max_length=20)

    def __str__(self):
        return self.number

phonebook/contacts/forms.py
from django import forms

from .models import Contact, PhoneNumber


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ["name"]


class PhoneNumberForm(forms.ModelForm):
    class Meta:
        model = PhoneNumber
        fields = ["number"]


PhoneNumberFormSet = forms.modelformset_factory(PhoneNumber, form=PhoneNumberForm, extra=1)

phonebook/contacts/views.py
from django.db import transaction
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView

from .forms import PhoneNumberForm, PhoneNumberFormSet
from .models import Contact, PhoneNumber


class ContactCreateView(CreateView):
    model = Contact
    fields = ["name"]
    template_name = "contacts/contact_form.html"
    success_url = reverse_lazy("contacts:contact_list")

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["phone_numbers"] = PhoneNumberFormSet(self.request.POST)
        else:
            data["phone_numbers"] = PhoneNumberFormSet()
        return data

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        context = self.get_context_data()
        phone_numbers = context["phone_numbers"]
        with transaction.atomic():
            self.object = form.save()
            if phone_numbers.is_valid():
                phone_numbers.instance = self.object
                phone_numbers.save()
        return super().form_valid(form)


class PhoneNumberCreateView(CreateView):
    model = PhoneNumber
    form_class = PhoneNumberForm
    template_name = "contacts/phone_number_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["contact"] = Contact.objects.get(pk=self.kwargs["pk"])
        return context

    def form_valid(self, form):
        form.instance.contact = Contact.objects.get(pk=self.kwargs["pk"])
        response = super().form_valid(form)
        return response

    def get_success_url(self):
        return reverse("contacts:contact_detail", args=[self.object.contact.pk])


class ContactListView(ListView):
    model = Contact
    template_name = "contacts/contact_list.html"
    context_object_name = "contacts"


class ContactDetailView(DetailView):
    model = Contact
    template_name = "contacts/contact_detail.html"
    context_object_name = "contact"

phonebook/contacts/templates/contacts/contact_detail.html
{% extends 'base.html' %} {% block content %}
<h2>{{ contact.name }}</h2>
<h3>Phone Numbers:</h3>
{% if contact.phone_numbers.all %}
<ul>
  {% for phone_number in contact.phone_numbers.all %}
  <li>{{ phone_number.number }}</li>
  {% endfor %}
</ul>
{% else %}
<p>No phone numbers found.</p>
{% endif %}

<a
  href="{% url 'contacts:phone_number_create' contact.id %}"
  class="btn btn-primary"
  >Add Phone Number</a
>
{% endblock %}

phonebook/contacts/templates/contacts/contact_form.html
{% extends 'base.html' %} {% block content %}
<h2>Add Contact</h2>
<form method="post">
  {% csrf_token %} {{ form.as_p }} {{ phone_number_formset.management_form }}

  <table class="table">
    {{ phone_number_formset.as_table }}
  </table>

  <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}

phonebook/contacts/templates/contacts/contact_list.html
{% extends 'base.html' %} {% block content %}
<h2>Contact List</h2>
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Phone Numbers</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for contact in contacts %}
    <tr>
      <td>{{ contact.id }}</td>
      <td>{{ contact.name }}</td>
      <td>
        {% for phone_number in contact.phone_numbers.all %} {{ phone_number.number }}<br />
        {% empty %} No phone numbers found. {% endfor %}
      </td>
      <td>
        <a
          href="{% url 'contacts:contact_detail' contact.id %}"
          class="btn btn-info"
          >View</a
        >
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="4">No contacts found.</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

phonebook/contacts/templates/contacts/phone_number_form.html
{% extends 'base.html' %} {% block content %}
<h2>Add Phone Number for {{ contact.name }}</h2>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}